<?php

/**
 * Implements hook_views_api().
 */
function views_date_format_sql_views_api() {
  return array(
    'api' => 3,
  );
}

/**
 * Implements hook_autoload_info().
 */
function views_date_format_sql_autoload_info() {
  return array(
    'views_date_format_sql_handler_date' => 'includes/views_date_format_sql_handler_date.inc',
    'views_date_format_sql_handler_date_field' => 'includes/views_date_format_sql_handler_date_field.inc',
  );
}

/**
 * Helper to retrieve the format to a given date format name.
 * see includes/common.inc:function format_date()
 */
function _views_date_format_sql_get_date_format($type = 'medium', $format = '') {
  $config_date = config('system.date');
  switch ($type) {
    case 'short':
      $format = $config_date->get('formats.short.pattern');
      break;

    case 'long':
      $format = $config_date->get('formats.long.pattern');
      break;

    case 'custom':
      // No change to format.
      break;

    case 'medium':
    default:
      // Retrieve the format of the custom $type passed.
      if ($type != 'medium') {
        $format = $config_date->get('formats.' . $type . '.pattern');
      }
      // Fall back to 'medium'.
      if (!$format) {
        $format = $config_date->get('formats.medium');
      }
      break;
  }
  return $format;
}
